- name: Create www group
  group: name=www state=present  

- name: Add deployment user
  user: name=deploy state=present password={{ deploy_password }} shell=/bin/bash group=www  

- name: Setup authorized_keys for user who may act as deploy user
  authorized_key: user=deploy key="{{ item }}"
  with_file:
    - ssh/id_rsa.pub

- name: Remove sudo group rights
  action: lineinfile dest=/etc/sudoers regexp="^%sudo" state=absent

- name: Add deploy user to sudoers
  action: lineinfile dest=/etc/sudoers regexp="deploy ALL" line="deploy ALL=(ALL:ALL) ALL" state=present    

- name: Disallow root SSH access
  action: lineinfile dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
  notify: restart ssh  

- name: Disallow password authentication
  action: lineinfile dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
  notify: restart ssh   
